version: '3'

services:
  redis:
    image: redis
    networks:
      - picsellia

  worker-service:
    image: picsellia-worker
    build:
      context: ./
      dockerfile: worker_service/Dockerfile
    command: celery -A celery_app.celery worker -Q outline -P threads
    depends_on:
      - redis
    networks:
      - picsellia

  api-service:
    image: picsellia-api
    build:
      context: ./
      dockerfile: api_service/Dockerfile
    ports:
      - "8011:80"
    depends_on:
      - redis
    networks:
      - picsellia
    environment:
      - ENV=local

networks:
  picsellia:
